name: docker_push
on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/*"
      - "docs/*"
      - "load-tests"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: publish
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u daniellarsennz --password-stdin
          docker build . -t "daniellarsennz/helloaspdotnetcore:latest" -t "daniellarsennz/helloaspdotnetcore:${{ github.sha }}"
          docker push "daniellarsennz/helloaspdotnetcore:latest"
        shell: bash
