name: docker_push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: chmod +x ./publish.sh
        shell: bash

      - name: publish
        run: ./publish.sh
        shell: bash
